export const botList = [
    "cryptoKing98",
    "politicalPundit",
    "WealthWizard",
    "alphaMale101",
    "gambleGuru",
    "HoopsHero23",
    "crimeChaser",
    "bitcoinBaller",
    "policyPro",
    "RichesGalore",
    "manlyMaverick",
    "casinoCraze",
    "dunkMaster45",
    "underworldU",
    "blockchainBoss",
    "govtGuru",
    "financeFanatic",
    "masculineMark",
    "pokerPrince",
    "bballFanatic",
    "lawbreakerLeo",
    "ethereumEddie",
    "civicSavvy",
    "investKing",
    "manPowerMax",
    "slotMachineSam",
    "jumpShotJake",
    "shadowShawn",
    "cryptoChad",
    "electionExpert",
    "moneyMogul",
    "toughGuyTom",
    "blackjackBilly",
    "basketballBen",
    "crimeHunter",
    "satoshiSam",
    "politicoPaul",
    "richGuyRay",
    "machoMike",
    "rouletteRick",
    "hoopDreamsDan",
    "feloniousFrank",
    "altcoinAndy",
    "debateDiva",
    "netWorthNate",
    "strongSteve",
    "bettingBob",
    "dribbleDarren",
    "mafiaMike",
    "cryptoQueen",
    "govtGal",
    "financeFiona",
    "manlyMatt",
    "wagerWill",
    "basketBabe",
    "crimeCatcher",
    "coinCollector",
    "policyPat",
    "investIvy",
    "manModeMitch",
    "pokerProPete",
    "fukbills",
    "crookCarter",
    "digitalDollars",
    "electionEmma",
    "wealthyWendy",
    "muscleMax",
    "casinoQueen",
    "jumpShotJill",
    "robberRon",
    "blockchainBabe",
    "politicoPete",
    "moneyMakerMia",
    "masculineMitch",
    "blackjackBrenda",
    "hoopsHannah",
    "crimeStopper",
    "cryptoGenius",
    "govtGuy",
    "financeFrank",
    "manlyMason",
    "rouletteRita",
    "dunkDylan",
    "crimeBuster",
    "coinMaster",
    "policyPete",
    "richGirlRita",
    "manModeMatt",
    "bettingBen",
    "hoopDreamsHank",
    "lawbreakerLiam",
    "altcoinAlex",
    "civicChris",
    "investmentIke",
    "strongSam",
    "slotQueen",
    "basketBaller",
    "crimeWatcher",
    "digiCrypto99",
    "govtWiz",
    "wealthGenius77",
    "alphaKing123",
    "SunnyVibes34",
  "JakeTravels",
  "TechGuru23",
  "LexiEats",
  "Wanderlust_John",
  "MusicMaven78",
  "FitFanatic_89",
  "BookishBella",
  "GamerGal57",
  "TrendyTara",
  "PhotoFanatic88",
  "CoolCat",
  "CodeMaster007",
  "NatureLover54",
  "FitLifeAlex",
  "CoffeeAddict2000",
  "DreamChaser_Liz",
  "InstaStar21",
  "UrbanExplorerX",
  "PeacefulPanda3",
  "SoundtrackSam",
  "CraftyCorner45",
  "TravelTina",
  "DigitalNomadBen",
  "DanceDiva99",
  "BloggerBree",
  "RunningRyan",
  "ChefChris85",
  "SparkleQueen_12",
  "ArtsyAnna",
  "JessieCoolCat",
  "HackerHarry",
  "BeautyBossBabe",
  "FashionFrenzy21",
  "GameChanger_92",
  "MovieManiac50",
  "FitnessNinja",
  "StyleIcon_Clara",
  "SportySpice13",
  "TomTheTechie",
  "AdventureAlex",
  "GardenGuruGail",
  "BookLoverLou",
  "CraftyCassie44",
  "FitFreak_Jane",
  "NomadNina",
  "YogaYogi_Emily",
  "BlissfulBakerZoe",
  "TrendSetter007",
  "GamerGuy_42",
  "CarlTheCreator",
  "FoodieFrank",
  "TimeToTravel",
  "HealthyHannah",
  "CharlieCooks",
  "AmyTheArtist",
  "FashionistaFaith",
  "NatureNerdNina",
  "CraftyCathy23",
  "HappyHeather",
  "TrendyTammy",
  "RunningRandy",
  "BlissfulBella",
  "StylishSophie99",
  "TravelTina",
  "BeautyBuff33",
  "MusicMagic77",
  "FitnessFreakX",
  "InfluencerIvy",
  "TechTrends_Tom",
  "AidenAdventures",
  "CraftyKaren9",
  "PeacefulPatty",
  "HealthyHolly",
  "CoolCody12",
  "ArtAdmirer24",
  "MovieManSam",
  "NatureNutNathan",
  "StyleStar22",
  "YogaYana_15",
  "FoodieFanatic",
  "DreamyDiane",
  "UrbanUla",
  "GardenGalGina",
  "BlissfulBen",
  "DigitalDave_99",
  "TaraTrends",
  "TechieTina",
  "SavvySarah",
  "FashionFiendFinn",
  "FoodieFun23",
  "MovieMagicMia",
  "CraftyCara",
  "YogaYvette",
  "CryptoSavvy87",
  "Politiclol",
  "WealthWise123",
  "AlphaAchiever",
  "GambleGenius",
  "HoopsHustler23",
  "CrimeCrusher",
  "BitcoinBoss",
  "PolicyProdigy",
  "RichesRuler",
  "ManlyMaverick99",
  "CasinoConnoisseur",
  "DunkDynamo45",
  "profit1",
  "BlockchainBaller",
  "GovtGuru27",
  "FinanceFan23",
  "MightyMasculine",
  "PokerProphet123",
  "BallinBaller",
  "LawlessLeader",
  "EthereumEagle",
  "CivicCitizen",
  "InvestmentInsider",
  "MaximusManhood",
  "SlotSensation",
  "jumpshoper5",
  "ShadowStriker",
  "CryptoChampion",
  "ElectionExpertise",
  "MoneyMagnate",
  "ToughTycoonTom",
  "Bjoblover",
  "BasketballBaller",
  "CrimeCrusader",
  "SatoshiSensation",
  "PolicyPioneer",
  "RichRichie",
  "MachoMogul",
  "RouletteRingleader",
  "HoopHeroDan",
  "FeloniousFinesse",
  "AltcoinA",
  "DebateDynamo",
  "mango27",
  "Stumykla",
  "Shipku",
  "Bobr2",
  "polish5",
  "Matkuboze",
  "ratatui",
    "Makaronek",
    "Kotlet",
  "WealthWizardNate",
  "StrengthSupreme",
  "BettingBarracuda",
  "DribbleDynamo",
  "MafiaMaverick",
  "CryptoConnoisseur",
  "GovtGalaxy",
  "FinanceFinesse",
  "ManlyMagnate",
  "WealthyWagerer",
  "BasketballBabe",
  "CrimeCatcher",
  "PolicyPilot",
  "InvestorIvy",
  "ManModeMaster",
  "PokerProphetPete",
  "Baller13",
  "CrookCatcher",
  "DigitalDollarDon",
  "ElectionEnthusiast",
  "WealthyWendy",
  "MuscleMaximus",
  "CasinoConnoisseur",
  "RobberRogue",
  "BlockchainBabe",
  "PoliticoPro",
  "MoneyMintMaker",
  "MasculineMarvel",
  "BlackjackBella",
  "HoopsHustlerHannah",
  "CrimeCleanser",
  "CryptoCzar",
  "GovtGallant",
  "FinanceFalcon",
  "ManlyMogul",
  "RouletteRuler",
  "DunkDynasty",
  "CrimeCleanser",
  "CoinCaptain",
  "PolicyPioneer",
  "RichGirlRita",
  "ManModeMax",
  "BettingBossBen",
  "HoopHeroHank",
  "Lawlessxd",
  "AltcoinAdmirer",
  "CivicCaptain",
  "InvestorInsight",
  "StrongSavior",
  "SlotSultan",
  "BasketballBeast",
  "CrimeCatcher",
  "CryptoChampion",
  "GovtGuru",
  "WealthWizard",
  "Alpha23",
  "Crypto99",
  "Wealthy1",
  "BitKing",
  "CoinFlip",
  "Bullion",
  "Richie7",
  "Macho22",
  "Alpha77",
  "BetMax1",
  "DiceMan",
  "Jumper3",
  "Hoops24",
  "Swish88",
  "Rebound",
  "Dunk123",
  "Mafia89",
  "Bandit2",
  "OutlawX",
  "Senator",
  "GovChief",
  "Prez2024",
  "Politik",
  "Debate7",
  "PollWin",
  "Hedge01",
  "Money44",
  "GainzUp",
  "Fortune",
  "SavRite",
  "LuxLife",
  "StashIt",
  "Mascul8",
  "DudeMan",
  "IronMus",
  "HeroGuy",
  "BetNow4",
  "Poker99",
  "RollWin",
  "JackerX",
  "Crypto7",
  "PrimeMe",
  "Stack1r",
  "Power99",
  "RichGuy",
  "Trader1",
  "Boss8Up",
  "FitMan1",
  "Mafia77",
  "Risker3",
  "Hoops99",
  "Coin2Day",
  "Wealth4U",
  "BitRage",
  "CryptoQ",
  "CashKing",
  "GoldUp1",
  "RichBoy",
  "Macho42",
  "AlphaX2",
  "BetWin9",
  "DicePro",
  "JumpMan",
  "HoopGuy",
  "Swish3r",
  "Reb0und",
  "Dunk24",
  "Mafioso",
  "Bandit8",
  "Outlaw7",
  "Sen8tor",
  "GovtMan",
  "Prez203",
  "PoliTic",
  "DebateX",
  "PollTop",
  "Hedge77",
  "Money4U",
  "GainMan",
  "Fortu42",
  "SavMon",
  "LuxGo99",
  "Stash22",
  "MscleUp",
  "DudeX1",
  "IronHrt",
  "HeroGuy9",
  "BetWin4",
  "Poker88",
  "Roll23",
  "Jackpot",
  "Bit007",
  "Prime99",
  "Stacked",
  "PowerX1",
  "RichOne",
  "TradeUp",
  "BossMan",
  "FitPro1",
  "MafiaX9",
  "RiskIt8",
  "Hoops77",
  "BitGold",
  "Wealthy7",
  "CryptoX",
  "CoinWin",
  "RichGuy1",
  "Gold4Us",
  "Macho99",
  "Alpha23",
  "BetKing",
  "Dice4Me",
  "Jump88",
  "Hoops1X",
  "Swish9",
  "Reboun8",
  "DunkMan",
  "Mafios0",
  "Bandit3",
  "Outlaw5",
  "Senatr2",
  "GovtX9",
  "PrezMan",
  "PolXtic",
  "Debat3r",
  "PolL1T",
  "Hedge99",
  "Mon3yUp",
  "Gain77",
  "Fortun8",
  "SavrU1",
  "Lux4U88",
  "Stash99",
  "Mscle1X",
  "DudeMan",
  "IronMus",
  "Hero123",
  "BetN0w4",
  "Poker4U",
  "Roll99",
  "JackX2",
  "BitMan9",
  "Prim3Up",
  "Stack88",
  "PowrUp2",
  "RichBoi",
  "Trad3X9",
  "BosMan7",
  "Fit4Me",
  "MafiaX4",
  "RiskUp1",
  "HoopX3",
  "BitWin",
  "RichMan",
  "CoinX",
  "Goldie7",
  "Wealthy2",
  "CryptoQ",
  "Bull3",
  "BitGuru",
  "CoinPro",
  "Alpha2X",
  "Macho5",
  "BetStar",
  "DiceX",
  "Jump99",
  "Hoops4U",
  "Swish7",
  "Rebnd3",
  "Dunk8",
  "Mafioso",
  "Bandt2",
  "OutXlaw",
  "Senatr8",
  "GovChf",
  "Prez2",
  "Poli3t",
  "Debat7",
  "PollX",
  "HedgX9",
  "MonUp",
  "Gainz",
  "Fort4u",
  "Savvy",
  "Lux9Up",
  "Stash7",
  "Mscle",
  "Dude4u",
  "IronM",
  "Hero77",
  "BetNow3",
  "PokerX1",
  "Roll2U",
  "Jack8",
  "BitBoy",
  "Prime4",
  "Stackx",
  "PowX2",
  "Rich5",
  "TradeU",
  "BosM4",
  "Fit8",
  "Mafia4",
  "Risk3",
  "Hoop4",
  "Cash9",
  "Wealth1",
  "BitSavy",
  "CoinN1",
  "Crypto8",
  "GoldX",
  "Alpha7",
  "BetWin8",
  "Dice4",
  "JumpX",
  "HoopsX",
  "Swish1",
  "RebX",
  "DunkX2",
  "MafX",
  "BandX2",
  "Out5",
  "Sen4",
  "Gov4U",
  "PrezX",
  "PolX",
  "Deb1",
  "Poll4",
  "Hdg8",
  "Mon7",
  "Gain2",
  "FortX",
  "Sav4U",
  "LuxX",
  "Stsh",
  "Dud4U",
  "IrnM",
  "Her9",
  "BtNw",
  "PokX",
  "Rl2U",
  "BitB",
  "Pri4",
  "Stkx",
  "RichB",
    "StarGzr",
    "ArtLvr9",
    "BookWrm",
    "Chef7",
    "TravelX",
    "EcoWarr",
    "Techie1",
    "Hiker99",
    "Yoga4U",
    "MusiC88",
    "DanceX1",
    "PhotoG2",
    "Gam3r1",
    "FitLife",
    "BioGeek",
    "MedStud",
    "HistFan",
    "NewsGuy",
    "FilmBuff",
    "SportX9",
    "RunFast",
    "Cycle77",
    "WriteOn",
    "Code99",
    "MathWiz",
    "Sci4U",
    "EcoHero",
    "PlantIt",
    "Green99",
    "CosmosX",
    "Cloud99",
    "DataPro",
    "DevLife",
    "GameOn1",
    "Art123",
    "Sketch9",
    "PaintMe",
    "Cook4U",
    "BakeX",
    "TripX99",
    "Globe77",
    "Enviro9",
    "Trek4U",
    "FitRun",
    "YogPro1",
    "SingX",
    "Tune77",
    "PicPro8",
    "GamerX2",
    "LifeFit",
    "BioX",
    "MedX2",
    "Hist88",
    "JournX",
    "Movie9",
    "Sport1",
    "Run99",
    "BikePro",
    "WriteIt",
    "Coder77",
    "MathX",
    "SciGuy",
    "Earth4U",
    "Plantr1",
    "GreenX",
    "Star99",
    "SkyX2",
    "Cloud7",
    "DataX",
    "DevX2",
    "PlayX1",
    "Draw99",
    "Paint77",
    "CookIt",
    "BakePro",
    "JetSet1",
    "World99",
    "EcoX2",
    "Trek88",
    "FitPro8",
    "YogMan",
    "SongX",
    "TuneIt",
    "PicX1",
    "Game99",
    "LiveFit",
    "BioGeek",
    "MedX9",
    "HistPro",
    "NewsX1",
    "FilmX99",
    "Sporty7",
    "RunX2",
    "CyclX99",
    "Writex1",
    "Dev4U",
    "Math99",
    "Sci99",
    "EnvX",
    "SpyMstr",
  "HackrX",
  "RusSpy1",
  "USA4Life",
  "DrugX99",
  "Intel77",
  "CrimeX",
  "FBI4U",
  "CIAx007",
  "MafiaX1",
  "Gang88",
  "Thief99",
  "RusHax",
  "USASec",
  "Agent47",
  "Narc123",
  "SpyGuy9",
  "HackIt",
  "Rus99",
  "AmerX",
  "Intel8",
  "Crime7",
  "FedX4U",
  "SpyPro",
  "DrugLrd",
  "HaxPro",
  "RusFdr",
  "USANow",
  "AgentX1",
  "ThugL4",
  "IntelX",
  "Crime99",
  "FBIX2",
  "SpyNow",
  "Drug77",
  "HackX3",
  "RusGov",
  "USAFed",
  "MoleX1",
  "CrimX",
  "FBI007",
  "MafX99",
  "ThugX9",
  "RusSpy",
  "USAHax",
  "Intel77",
  "CIA007",
  "MafX2",
  "Crime4U",
  "Hax007",
  "Rus8X",
  "USA99",
  "Agnt47",
  "NarcX",
  "Spyz99",
  "Hackr1",
  "Rus007",
  "US4Fed",
  "Sp4yX1",
  "DrugL9",
  "Crim3X",
  "FBIX9",
  "SpyPro7",
  "DrugIt",
  "Hax4U",
  "RusSpy",
  "USFed",
  "IntelX9",
  "CrimX1",
  "FedX77",
  "Spy007",
  "DrugX",
  "Hack99",
  "RusX77",
  "USA4U",
  "AgntX1",
  "Thug9X",
  "Intel2",
  "Crim99",
  "FBI9X",
  "SpyzX1",
  "Drug99",
  "HackX",
  "RusX3",
  "USSpy",
  "Mole77",
  "CrimX9",
  "FedX99",
  "MafPro",
  "ThugX",
  "RusIntel",
  "USAHax",
  "CIA7X1",
  "Spyx99",
  "DrgX2",
  "Hack77",
  "RusX",
  "US99",
  "AgntX",
  "Euro99",
  "FrnceX",
  "Ger4U",
  "Spain77",
  "ItlyPro",
  "Neth007",
  "Swed99",
  "NorwayX",
  "Swiss7",
  "Grc123",
  "PolandX",
  "Irelnd9",
  "UkEng1",
  "ScotX",
  "Wales7",
  "Portgl4",
  "BelgX",
  "DenX",
  "Austria1",
  "CzRep88",
  "Slovk9",
  "CroaX",
  "BulgX",
  "Romn77",
  "HngryX",
  "Est99",
  "LatviaX",
  "LituaX",
  "Finland1",
  "Ice7X",
  "RussX",
  "UkrX",
  "BelraX",
  "SerbX2",
  "BosX99",
  "Mont9",
  "AlbanX1",
  "Mace99",
  "SlovniaX",
  "MaltX7",
  "Cyprs1",
  "Lux9X",
  "Monaco7",
  "AndraX",
  "VaticX1",
  "SanMar7",
  "Liech99",
  "KosvX",
  "Moldv1",
  "GeorX",
  "AzerX2",
  "ArmX88",
  "KazX77",
  "TurkyX",
  "Amigo99",    // Spanish for "friend"
  "Bonjour",    // French for "hello"
  "Danke77",    // German for "thank you"
  "CiaoX1",     // Italian for "hello/goodbye"
  "NinoX",      // Spanish for "child"
  "Luz123",     // Spanish for "light"
  "Blume99",    // German for "flower"
  "TerraX",     // Italian for "earth"
  "Fuego77",    // Spanish for "fire"
  "Vino4U",     // Italian for "wine"
  "SolX",       // Spanish for "sun"
  "Mundo9",     // Spanish for "world"
  "Rosa77",     // Italian for "rose"
  "SaludX1",    // Spanish for "health"
  "Fiore99",    // Italian for "flower"
  "Gratias",    // Latin for "thanks"
  "AquaX1",     // Latin for "water"
  "Liebe77",    // German for "love"
  "Paz999",     // Spanish for "peace"
  "Soleil",     // French for "sun"
  "TierraX",    // Spanish for "earth"
  "RanaX",      // Spanish for "frog"
  "Cielo77",    // Spanish for "sky"
  "Luna4U",     // Italian for "moon"
  "Himmel9",    // German for "sky"
  "MareX1",     // Italian for "sea"
  "Gato99",     // Spanish for "cat"
  "Cerve7",     // Spanish for "beer" (short for "cerveza")
  "ChienX",     // French for "dog"
  "Toro77",     // Spanish for "bull"
  "Ola123",     // Portuguese for "hello"
  "Bacio99",    // Italian for "kiss"
  "FelizX",     // Spanish for "happy"
  "Amica77",    // Italian for "friend" (female)
  "Brot999",    // German for "bread"
  "BruderX",    // German for "brother"
  "VentoX",     // Italian for "wind"
  "Feuer77",    // German for "fire"
  "HogarX",     // Spanish for "home"
  "Frere99",    // French for "brother"
  "VivaX1",     // Spanish for "live"
  "Nube777",    // Spanish for "cloud"
  "Nacht99",    // German for "night"
  "Dia123",     // Spanish for "day"
  "TempoX",     // Italian for "time"
  "Citta99",    // Italian for "city"
  "Cavalo7",    // Portuguese for "horse"
  "LagoX1",     // Italian for "lake"
  "Serra77",    // Portuguese for "mountain range"
  "PlayaX",     // Spanish for "beach"
  "NinoX7",     // Spanish for "child"
  "Reina99",    // Spanish for "queen"
  "Herz777",    // German for "heart"
  "ReiseX1",    // German for "travel"
  "Llibre9",    // Catalan for "book"
  "Corsa77",    // Italian for "race"
  "Pulpo99",    // Spanish for "octopus"
  "OuroX1",     // Portuguese for "gold"
  "SombraX",    // Spanish for "shadow"
  "Piedra9",    // Spanish for "stone"
  "Mele777",    // Italian for "apples"
  "Vento99",    // Portuguese for "wind"
  "ArbolX1",    // Spanish for "tree"
  "Fiesta7",    // Spanish for "party"
  "Girasol" ,
  "Lion77",
  "AppleX",
  "Faith99",
  "Tiger4U",
  "Peach9",
  "BibleX1",
  "Bear123",
  "Mango7",
  "PrayX",
  "Eagle99",
  "BerryX1",
  "Saint77",
  "WolfX1",
  "Grape9",
  "TempleX",
  "Shark77",
  "PlumX2",
  "Spirit1",
  "Fox99",
  "Citrus7",
  "AngelX1",
  "Deer123",
  "MelonX",
  "Bless77",
  "Horse4U",
  "CherryX",
  "Glory99",
  "PandaX1",
  "Banana9",
  "Divine1",
  "Falcon77",
  "OliveX2",
  "Church7",
  "Zebra99",
  "PapayaX",
  "Psalm99",
  "Whale4U",
  "KiwiX1",
  "Grace77",
  "Jaguar7",
  "Berry99",
  "HymnX1",
  "EagleX2",
  "Fruit77",
  "HolyX99",
  "Rhino4U",
  "Apple1X",
  "Peace77",
  "Giraffe9",
  "PeachX2",
  "Faith123",
  "Monkey7",
  "MangoX",
  "Bible99",
  "Leopard4",
  "Grape99",
  "SaintX",
  "Dolphin7",
  "Plum99",
  "Pray123",
  "TurtleX1",
  "Citrus9",
  "Spirit77",
  "Bison99",
  "MelonX1",
  "Bless9",
  "Parrot4U",
  "Cherry1",
  "Glory7",
  "OtterX99",
  "BananaX",
  "Divine77",
  "FalconX1",
  "Olive7",
  "Church99",
  "Koala4U",
  "Papaya99",
  "PsalmX1",
  "Snake7",
  "Kiwi123",
  "Grace99",
  "BearX77",
  "FruitX1",
  "Holy777",
  "Frog99",
  "Apple77",
  "Peace123",
  "Hawk4U",
  "Peach99",
  "FaithX",
  "LynxX77",
  "Mango4",
  "Bible777",
  "LemurX1",
  "Grape7",
  "Saint99",
  "jonas",
  "james4x",
  "sigis",
  "tarzanas",
  "antiloser",
  "andrewtate",
  "matrix",
  "ronaldo7",
  "messi10",
  "emigrantas",
  "anonymousx",
  "pokerface"
  ]
  
export const botUsernamesList = botList.map(bot => bot.toLowerCase())




export const namesBlacklist = [
    "Bitcoin", "anonymous", "profit", "bobr", "Ethereum", "Blockchain", "Cryptocurrency", "Wallet", "Mining", "Token", "NFT", "Decentralized", "Altcoin", "Ledger", "Satoshi", "Digital", "Coin", "HODL", "SmartContract", "DeFi",
    "Government", "Democrat", "Republican", "Election", "Policy", "Democracy", "Congress", "Senator", "President", "PrimeMinister", "Legislation", "Campaign", "Debate", "Governance", "Constitution", "Bipartisan", "Lobbyist", "Diplomacy",
    "Rich", "Wealthy", "Millionaire", "Billionaire", "Prosperity", "Fortune", "Success", "Abundance", "Assets", "Capital", "Portfolio", "Investment", "Financial", "Estate", "NetWorth", "WealthManagement",
    "Man", "Male", "Strength", "Muscle", "Macho", "Tough", "Courage", "Warrior", "Alpha", "Dominance", "Virility", "Fitness", "Athlete", "Power", "Bravery", "Bold", "Resilience", "Honor", "Confidence",
    "Casino", "Bet", "Poker", "Blackjack", "Roulette", "Slot", "Jackpot", "Chips", "Gamble", "Risk", "Chance", "Odds", "House", "Stake", "Prize", "Fortune", "Luck",
    "Hoop", "Dunk", "Ball", "Player", "Team", "NBA", "Slam", "Score", "Rebound", "Pass", "Defense", "Offense", "Coach", "MVP", "Game", "Tournament", "Championship", "Dribble",
    "Crime", "Criminal", "Gang", "Thief", "Robbery", "Theft", "Heist", "Fraud", "Illegal", "Jail", "Prison", "Felon", "Offender", "Convict", "Wanted", "Fugitive", "Suspect", "Accomplice", "Conspiracy",
    "Success", "Innovation", "Influencer", "Entrepreneur", "Startup", "Tech", "Trend", "Digital", "Global", "Network", "Community", "Empower", "Impact", "Sustainability", "Leadership", "Innovation", "Creativity", "Future", "Progress"
  ]

export const botBetAmounts = [
    0.10,
    0.20,
    0.2,
    0.2,
    0.40,
    0.44,
    0.45,
    0.05,
    0.01,
    0.1,
    0.14,
    0.15,
    0.16,
    0.02,
    0.03,
    0.04,
    0.01,
    0.02,
    0.03,
    0.04,
    0.05,
    0.06,
    0.07,
    0.08,
    0.09,
    0.10,
    0.15,
    0.20,
    0.2,
    0.2,
    0.2,
    0.3,
    0.3,
    0.3,
    0.3,
    0.4,
    0.4,
    0.4,
    0.4,
    0.05,
    0.50,
    0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.49,
     0.60,
      0.70, 0.7, 0.7, 0.7,
      0.77, 0.78, 0.79, 0.80,
      0.95, 0.98,
      0.70, 0.7, 0.7, 0.7,
      0.77, 0.78, 0.79, 0.80,
      0.95, 0.98,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
    10.50, 11.00, 11.50, 12.00, 12.50, 13.00, 13.50, 14.00, 14.50, 15.00, 15.50, 16.00, 16.50, 17.00, 17.50, 18.00, 18.50, 19.00, 19.50, 20.00, 30, 
    10.50, 11.00, 11.50, 12.00, 12.50, 13.00, 13.50, 14.00, 14.50, 15.00, 15.50, 16.00, 16.50, 17.00, 17.50, 18.00, 18.50, 19.00, 19.50, 20.00, 30, 
    
    
    0.10,
    0.20,
    0.2,
    0.2,
    0.40,
    0.44,
    0.45,
    0.05,
    0.01,
    0.1,
    0.14,
    0.15,
    0.16,
    0.02,
    0.03,
    0.04,
    0.2,
    0.05,
    0.50,
    0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.49,
     0.60,
      0.70, 0.7, 0.7, 0.7,
      0.77, 0.78, 0.79, 0.80,
      0.95, 0.98,
      0.70, 0.7, 0.7, 0.7,
      0.77, 0.78, 0.79, 0.80,
      0.95, 0.98,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
      0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10, 3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 4.60, 4.70, 4.80, 4.90, 5.00, 5.50, 6.00, 6.50, 7.00, 7.50, 8.00, 8.50, 9.00, 9.50, 10.00,
    10.50, 11.00, 11.50, 12.00, 12.50, 13.00, 13.50, 14.00, 14.50, 15.00, 15.50, 16.00, 16.50, 17.00, 17.50, 18.00, 18.50, 19.00, 19.50, 20.00, 30, 
    10.50, 11.00, 11.50, 12.00, 12.50, 13.00, 13.50, 14.00, 14.50, 15.00, 15.50, 16.00, 16.50, 17.00, 17.50, 18.00, 18.50, 19.00, 19.50, 20.00, 30, 
    
    
    
    
    
    40, 50, 60, 70, 80, 90, 100
  ]
  

export const botLivechatMessages = [
    'now red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'it is red',
    'now heart',
    'red now',
    'its def red',
    'its red',
    'its red now',
    'I know its red',
    'I hope its red',
    'I hope its red now',
    'red color',
    'red color now',
    'spin red',
    'spin red now',
    'red now',
    'give red',
    'i believe red xd',
    'pray for red',
    'gimme red',
    'red please',
    'red please now',
    'red',
    'RED',
    'RED!!!',
    'RED!',



    "Now black",
    "now dark",
    "once you go black you never go back",
    "roll chocolate",
    "roll black",
    "roll dark",
    "hit black",
    "black",
    "black now",
    "its def black",
    "Its black",
    "its black now",
    "I know its black",
    "I hope its black",
    "I hope its black now",
    "black color",
    "black color now",
    "spin black",
    "spin black now",
    "black now",
    "give black",
    "i believe black xd",
    "pray for black",
    "gimme black",
    "black please",
    "black please now",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "BLACK",
    "BLACK!!!",
    "BLACK!",




    "Now green",
    "now heart",
    "green now",
    "its def green",
    "its green",
    "its green now",
    "green color now",
    "pray for green",
    "green please",
    "rare green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "next green",
    "roll green",
    "spin green ",
    "NOW GREEN 100%",


    "red/green I see it",
    "red/green",



    'now red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'red',
    'it is red',
    'now heart',
    'red now',
    'its def red',
    'its red',
    'its red now',
    'I know its red',
    'I hope its red',
    'I hope its red now',
    'red color',
    'red color now',
    'spin red',
    'spin red now',
    'red now',
    'give red',
    'i believe red xd',
    'pray for red',
    'gimme red',
    'red please',
    'red please now',
    'red',
    'RED',
    'RED!!!',
    'RED!',



    "Now black",
    "now dark",
    "once you go black you never go back",
    "roll chocolate",
    "roll black",
    "roll dark",
    "hit black",
    "black",
    "black now",
    "its def black",
    "Its black",
    "its black now",
    "I know its black",
    "I hope its black",
    "I hope its black now",
    "black color",
    "black color now",
    "spin black",
    "spin black now",
    "black now",
    "give black",
    "i believe black xd",
    "pray for black",
    "gimme black",
    "black please",
    "black please now",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "BLACK",
    "BLACK!!!",
    "BLACK!",




    "Now green",
    "now heart",
    "green now",
    "its def green",
    "its green",
    "its green now",
    "green color now",
    "pray for green",
    "green please",
    "rare green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "next green",
    "roll green",
    "spin green ",
    "NOW GREEN 100%",


    "red/green I see it",
    "red/green",


    "dang it",
    "not again please",
    "not again",
    "damn",
    "dumping everything",
    "all or nothing xd",
    "unlucky day",
    "tell me what to bet",
    "I need a win",
    "fknig rigged roulette",
    "I hate this game",
    "today went from 5 to 80 coins and then lost it...",
    "I was up 100 coins and now I'm down 5 :(",
    "need more money",
    "shut up with ur predictions",
    "wtf is this",
    "stop gambling and buy your loved ones flowers",
    "all site members are manslovers or single",
    "miss all green",
    

    "why deposit over credit card is not working?",
    "bitcoin deposit takes so long",
    "deposit paypal?",
    "I want to deposit with skrill",
    "I need to withdraw or I will lose everything xd",
    "when will credit card deposit be available?",
    "add ethereum deposit..",
    "can i deposit usdt?",
    "can i cancel a withdraw?",
    "green ?",
    "shitty call",
    "3/4 so far",
    "go easy 4 times red",
    "red train will come",
    "i can't believe it",
    "green again",
    "lets go",
    "maybe green",
    "maybe red",
    "maybe black",
    "close",
    "close one",
    "NO WAY XD",
    "double dow worth",
    "damnnn",



    "am broke lol",
    "rip",


    "already empty pockets",
    "good day for me",
    "hot roulette",
    "stacked for weekend lol",

    "mozna zielony? xd",
    "daj priz",
    "lt yra? :D",
    "niech bedzie zielony",
    "Быстрее",
    "крути",
    "lol collapse",
    "bro nah",
    "bro wtf the live hahahah",
    "skill isuse",
    "big rock every day",
    "lool",
    "fkings gambling...",
    "what up",
    "have 2 acc on the site inlegal or legal?",
    "ah",
    "hello",
    "hi",
    "zero",
    "need that green fr",
    "i can afford midgets now",
    "im sick of this",
    "elon musk..",
    "fr",


    "no ghon be like 16 more spins",
    "lol",
    "now its green",
    "if no green in next 5 spins zolfi is gay",
    "has to be green",
    "my friend has win the 1k",
    "tf bro",
    "mf",
    "red/green",
    "*_*",
    "hi wsp",
    "mmmmmmmmmm",
    "lets see",
    "finland1 give coins please",
    "give me coins please",
    "anyone can give me 0.50 coins?",
    "go sleep",
    "so cringe",
    "bruh",
    "brooo",
    "its never green when i need it",
    "gtg",
    "im so back",
    "tired",
    "for me its all or nothing",
    "do people realize that home always win",
    "addictive",
    "need more coins",
    "i need to win",

    "give me coins",
    "green 100%",
    "this website has it out for me frfr",
    "BAITED :(",
    "fucking bait",
    "go now",
    "gg",
    "always when i bet green dead",
    "same",
    "bait=green",
    "This shit hurts",
    "pain is real",
    "betttt",
    "bettt its sure red",
    "fuck this shitr",
    "omg",
    "ez",
    "green!!!",
    "wtf man is this",
    "all in green rn go big",
    "unluck",
    "lucky day",
    "scripted...",
    "ate my whole balance",
    "rip coins you will be missed",
    "i will buy lambo",
    "all gone bruh",
    "rip balance",
    "rip coins",
    "rip lambo",
    "give me lambo",
    "please god gimme lambo",
    "its getting redicolous",
    "wake up",
    "dropped to 2",
    "mathg",
    "br",
    "crazy",
    "damn",
    "huge",
    "take the w",
    "gz",
    "Gz everyone",
    "its skill",
    "skill issue",
    "lucky asf",
    "heyy",
    "yo @finland1",
    "funds are safu",
    "R",
    "aa",
    "aint no way",
    "bank trades down?",
    "do a game",
    "get.",
    "xd",
    "day x",
    "what",
    "blet",
    "suka",
    "zajibali nx",
    "all in",
    "next red",
    "next black",
    "go black",
    "go red",
    "scam",
    "ye",
    "lag",
    "easy",
    "so hard",
    "bloody coins",
    "im hungry",
    "green right there woopies",
    "lucky i guess",
    "...",
    ".",
    "green",
    "i kenw",
    "someone give me 2 coins to bet pls",
    "aaa slide sum for a niga",
    

    "finally no kyc require",
    "is this site no kyc?",




    'I bet red, so its black now xd',
    'now green',
    'why no double',
    'azsem rossz',
    'ego down..',
    'more to come lets gooo',
    'ez again',
    'ezz green',
    'let me win ffs',
    'what the hel',
    'double it',
    'Wtf did say',
    'XD',
    'Bro',
    'red, thank me later',
    'black, thank me later',
    'green, thank me later',
    'red now again',
    'fuck me',
    'gg',
    'Gg',
    'game over',
    'its over :D',
    'EVERY FKING TIME',
    'for real dude',
    'get me outta here',
    'finland1, please give coins'

]
  